"""separate to services and channels

Revision ID: b9aa2d315d5b
Revises: 
Create Date: 2019-08-24 14:25:22.003187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9aa2d315d5b'
down_revision = '63e810297a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_jp', sa.String(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_channels_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels'))
    )
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_manual_reserved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_recording', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_programs_service_id_services'), 'services', ['service_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_programs_channel_id_channels'), 'channels', ['channel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_programs_channel_id_channels'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_programs_service_id_services'), type_='foreignkey')
        batch_op.drop_column('service_id')
        batch_op.drop_column('is_recording')
        batch_op.drop_column('is_manual_reserved')
        batch_op.drop_column('channel_id')

    op.drop_table('channels')
    op.drop_table('services')
    # ### end Alembic commands ###
