version: "3.7"

services:
  aircheq_operator:
    image: aircheq_operator:latest
    volumes:
      - type: bind
        source: "./config"
        target: "/opt/app/aircheq_config"
      - type: bind
        source: "./config/db"
        target: "/opt/app/aircheq_config/db"
      - type: bind
        source: "./config/logs"
        target: "/opt/app/aircheq_config/logs"
      - type: bind
        source: "./config/recorded"
        target: "/opt/app/aircheq_config/recorded"
    environment:
      - HOST_UID
      - HOST_GID
      - TZ=Asia/Tokyo
    restart: always

  aircheq_web:
    image: aircheq_web:latest
    volumes:
      - type: bind
        source: "./config"
        target: "/opt/app/aircheq_config"
      - type: bind
        source: "./config/db"
        target: "/opt/app/aircheq_config/db"
      - type: bind
        source: "./config/logs"
        target: "/opt/app/aircheq_config/logs"
      - type: bind
        source: "./config/recorded"
        target: "/opt/app/aircheq_config/recorded"
    expose:
      - "5000"
    ports:
      - "44100:5000"
    environment:
      - HOST_UID
      - HOST_GID
      - TZ=Asia/Tokyo
    restart: always
